name: WurmHelper_Dart
description: Wurm Online helper for action queue prompting
version: 0.0.1
author: Ashley Williamson <ashley@inp.io>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
